version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: maybe_web_1
      APP_PORT: 3063

  web:
    image: ghcr.io/maybe-finance/maybe:0.2.0@sha256:6b2471cb033e2f92f1eed33a64008c101ea36fd99c59b92b42083180c57fc83e
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/rails:/rails/storage
    environment:
      SELF_HOSTING_ENABLED: "true"
      PORT: 3063
      DB_HOST: db
      DB_PORT: 5432
      DATABASE_URL: postgres://maybe:maybe@db:5432/maybe
      RAILS_FORCE_SSL: "false"
      RAILS_ASSUME_SSL: "false"
      POSTGRES_DB: maybe
      POSTGRES_USER: maybe
      POSTGRES_PASSWORD: maybe
      GOOD_JOB_EXECUTION_MODE: async
      SECRET_KEY_BASE: $APP_SEED
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17@sha256:87ec5e0a167dc7d4831729f9e1d2ee7b8597dcc49ccd9e43cc5f89e808d2adae
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: maybe
      POSTGRES_USER: maybe
      POSTGRES_PASSWORD: maybe
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U maybe']
      interval: 10s
      timeout: 5s
      retries: 5